build: zyxcba.c pila.c cola.c lista.c hash.c abb.c heap.c strutil.c csv.c funciones_tp2.c
	 gcc -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o pruebas *.c

run: build
	./pruebas doctores.csv pacientes.csv
